// Every line the page says out loud. Each one is recorded once (tools/make-voice.mjs) with Kokoro-82M,
// an open-weight text-to-speech model, so every visitor hears the same natural voice in any browser.
export const LINES = {
  hello: 'Hello! Here is your plan for today.',
  feeling: 'Hello. How are you feeling today? Any feeling is okay.',
  thanks: 'Thank you for telling me. Would you like a calm break first, or shall we start gently?',
  calm: 'This is the calm corner. Breathe in as the circle grows. Breathe out as it gets smaller. Take all the time you need.',
  paused: 'Paused. Take your time. Your stars are saved.',
  break: 'Break time. Have some water or a snack. Stretch, move or rest. No work now.',
  wentwell: 'What went well today? Pick as many as you like.',
  chip1: 'I tried hard',
  chip2: 'I learned something new',
  chip3: 'I asked for help',
  chip4: 'I sounded out a hard word',
  chip5: 'I took a break when I needed one',
  chip6: 'I kept going',
  welldone: 'Well done!',
  listen: 'Listen to the parts. What word is it?',
  yes: 'Yes! That is right.',
  again: 'Listen again. Push the parts together.',
  build: 'Build the word. Tap the sounds in order.',
  built: 'You built the word!',
  notyet: 'Not yet. Say each sound and try again.',
  sounds: 'Say each sound, then the word.',
  changed: 'What changed?',
  first: 'Read the first word.',
  aloud: 'Read it out loud.',
  great: 'You did it. Great reading!',
  trying: 'Good trying. You kept going!',
  levelup: 'Level up! You unlocked a new friend and a new world.',
  finished: 'You finished today. See you next time!',
};
